# Generated by Django 4.1.2 on 2022-10-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Crypto.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorites',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Crypto.users'),
        ),
    ]
